### ISSUE TITLE
ssl url support

### ISSUE THREAD

**Issue by jo** [semantic-release/cli#10]
I usually use ssh urls, eg:
```json
"repository": {
  "type": "git",
  "url": "git+ssh://git@github.com/eHealthAfrica/couchdb-bootstrap.git"
}
```

This does not work with current semantic-release-cli@1.0.4:
```sh
Error: Invalid protocol: ssh:
```

**Comment by christophwitzko** [comment]
Hi @jo,

thank you for the bug report. This issue should be fixed in 65d4987.

have a nice day,
Christoph

**Comment by jo** [comment]
That was faster than I was able to type :+1: 

Thanks!

**Comment by christophwitzko** [comment]
Ups, I'm sorry. :confused:

**Comment by jo** [comment]
no - its all awesome :grinning:
