### ISSUE TITLE
Has anyone noticed the non-well-formed `<a name"...">` tag in the release notes?

### ISSUE THREAD

**Issue by uglow** [semantic-release/cli#103]
See [releases](https://github.com/semantic-release/cli/releases) for an example. The anchor tag is missing an `=` for the `name` attribute. E.g. `<a name"...">` instead of `<a name="...">`

**Comment by ethanneff** [comment]
related https://github.com/semantic-release/semantic-release/issues/363

**Comment by pvdlg** [comment]
Duplicate of semantic-release/semantic-release#363

**Comment by pvdlg** [comment]
Fixed in the latest `semantic-release`
