### ISSUE TITLE
init hangs when asking for GitHub username

### ISSUE THREAD

**Issue by coderbyheart** [semantic-release/cli#116]
I can not enter any character, or press enter.

Node version: v8.1.0
semantic-release-cli version: 3.0.3

**Comment by coderbyheart** [comment]
Could be related to https://github.com/nodejs/node/issues/13557

**Comment by js-n** [comment]
pretty sure that was a node 8.1.0 bug- should be fixed in 8.1.2+, can you confirm?

**Comment by coderbyheart** [comment]
Yes, works again with 8.1.2.
