### ISSUE TITLE
Confirm before overwriting .travis.yml

### ISSUE THREAD

**Issue by jo** [semantic-release/cli#12]
Or even merge if possible.

**Comment by remy** [comment]
+1!

I had a .travis.yml file setup, and it removed the services I needed the tests to run with. I caught it in the commit diff, but still - would be good to try and merge...if possible, or warn.

**Comment by boennemann** [comment]
Yep we'll address this somehow, and if only for the warning. Thanks for reporting!

**Comment by mprinc** [comment]
Same here, luckily I didn't trust it too much :) and saved it before.
Is it possible to just patch existing .travis.yml, you do not need complete control over it, right? just add a bit of after_success, etc

**Comment by finnp** [comment]
I think it would be great if it would modify an existing .travis.yml (so that things like `env` keys are not deleted).

**Comment by yamikuronue** [comment]
....Why would you presume to OVERWRITE something like that?! Yes, please merge!

**Comment by boennemann** [comment]
Closed via d2ac6dcbc954d85e58e8a946b76a778fbc2c4255
