### ISSUE TITLE
freezes on setup, have to manually kill.

### ISSUE THREAD

**Issue by mikeal** [semantic-release/cli#121]
I went to setup semantic-release on a new project. It asked for my npm credentials and then when it moved on to my GitHub username it froze. Can't type, can't ctrl-c to kill, had to open another terminal to kill it.

Now, when I try to run it again, it asks for my npm username, skips password and asks for GitHub username and freezes again no matter what.

<img width="429" alt="screen shot 2017-07-22 at 12 12 47 pm" src="https://user-images.githubusercontent.com/579/28492762-2295cef4-6ed7-11e7-9fce-5714005a0d76.png">

**Comment by gr2m** [comment]
Hmm I’ve never experienced that myself ... maybe try to run it with `npm_config_loglevel=verbose` it should show more information of what’s happening? What node / npm version are you using?

**Comment by mikeal** [comment]
<img width="700" alt="screen shot 2017-07-23 at 12 41 34 pm" src="https://user-images.githubusercontent.com/579/28502305-559ea1cc-6fa4-11e7-8e2d-613dabc38025.png">

**Comment by gr2m** [comment]
I was able to reproduce the bug with node v8.1.0 & npm 5.0.3

**Comment by gr2m** [comment]
but it worked in node v8.1.2 / npm v5.3.0, can you check?

**Comment by mikeal** [comment]
same :( 

<img width="700" alt="screen shot 2017-07-23 at 12 41 34 pm" src="https://user-images.githubusercontent.com/579/28502414-eca7e31a-6fa6-11e7-85b5-7d99fda5cc57.png">

**Comment by mikeal** [comment]
Fixed with latest Node.js.
