### ISSUE TITLE
.travis.yml: cache $HOME/.npm instead of node_modules

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cli#125]
that’s what the `npm` CLI core contributor recommend:
https://twitter.com/maybekatz/status/905213355748720640

I don’t know the exact details on this, but I trust Kat :)

**Comment by luftywiranda13** [comment]
AFAIK, it's the place where globally installed package located

**Comment by gr2m** [comment]
Yes. I just don’t know the exact ways that caching `node_modules` can cause problems like mentioned in the twitter thread linked above, but I was bitten by it myself in the past

**Comment by luftywiranda13** [comment]
me too, that's why I decided not to get it cached in my CI setup. grabbing fresh dependencies in CI helps to catch regression IMO

**Comment by gr2m** [comment]
yeah, but caching the `~/.npm` folder shouldn’t be a problem, right?

**Comment by pvdlg** [comment]
Closing as it was implemented
