### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by lifeiscontent** [semantic-release/cli#138]
Hey there!

I was wondering how I can fix my semantic release with this project?

you can see the build status here: https://travis-ci.org/lifeiscontent/backoff2

I'm new to semantic-release, any help would be appreciated. Thanks!

**Comment by gr2m** [comment]
hey the build looks good to me, the version was released to npm and the release was created on GitHub: https://github.com/lifeiscontent/backoff2/releases/tag/v1.1.0

Let us know if you have any further questions :)
