### ISSUE TITLE
Failed on private module/travis pro

### ISSUE THREAD

**Issue by remy** [semantic-release/cli#14]
Just went through the setup for travis-ci pro, and it just bails:

```shell
» semantic-release-cli setup                                                                                                    ◉ ◼◼◼◼◼◼◼◼◼◼
? Is the GitHub repository private? Yes
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? remy
? What is your npm email? remy@leftlogic.com
? What is your npm password? ******
? What is your GitHub username? remy
? What is your GitHub password? ************
? What is your GitHub two-factor authentication code? <removed>
? What CI are you using? Travis CI Pro
ERR! semantic-release Could not get repository on Travis CI.
ERR! semantic-release file not found
```

I wasn't sure if there was a verbose output that I could help with.

**Comment by boennemann** [comment]
Can you check whether a `~/.travis/config.yml` file exists on your disk?

**Comment by remy** [comment]
No, my bad. It was because travis pro didn't have access to the github org. I enabled access, and the setup passes.

**Comment by boennemann** [comment]
Alright, thanks! I just saw that the config.yml thing is inside try/catch anyway.

**Comment by michaellujan** [comment]
i'm getting the same error, my repo does have access but I do not have a .travis/config.yml file

**Comment by evansiroky** [comment]
I had this error, but recently renamed my github username so it wasn't finding my repo.  It worked once I corrected the repo info in my package.json file.
