### ISSUE TITLE
File not found and npm login issues

### ISSUE THREAD

**Issue by d3lm** [semantic-release/cli#187]
I am trying to use `semantic-release-cli` to setup my project but it always fails and gives me the following error after selecting Travis CI from the option menu:

```
ERR! semantic-release { file: 'not found' }
```

Also, every now and then I can't login to npm and get the following error:

```
ERR! semantic-release Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:160:7)
ERR! semantic-release  { Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:160:7)
ERR! semantic-release   stack: 'Error: Could not login to npm.\n    at getNpmToken (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)' }
```

Even when I setup a new package from scratch using `npm init` I get those errors.

Any idea?

**Comment by pvdlg** [comment]
Regarding `{ file: 'not found' }`, is it the same issue as #88? There is some advice over there about how to resolve this situation.

Regarding `Could not login to npm.` it's something we started to experience recently. It's quite sporadic and seems to be a problem on npm side.
We use the [npm-registry-client](https://github.com/npm/npm-registry-client) which already include a retry on fail mechanism. So I don't know if we can do anything else on our end.

**Comment by d3lm** [comment]
Thanks for the fast response! Really appreciated.

It seems that I had to re-activate my project on Travis side. But I never saw `ERR! semantic-release Could not get repository on Travis CI.`. Apparently there was a problem with the project on Travis CI but all I got was `Apparently`.  Now it seems to work. 

Thanks a lot and also for elaborating on the npm login issue.
