### ISSUE TITLE
Start semantic release at a specific version

### ISSUE THREAD

**Issue by lifeiscontent** [semantic-release/cli#211]
is there a way to tell semantic release to start from a specific version?

I just added semantic release to a previously non-automated released package and now its saying it wants to publish 1.0.0 which has already been published.

**Comment by pvdlg** [comment]
semantic-release uses Git tags to identify the last commit of a release.
If you already have releases you should make sure the corresponding commit is tagged with a tag named `v<version>` (for example `v2.0.0`).

**Comment by lifeiscontent** [comment]
@pvdlg thanks a lot for your help!

**Comment by jakobrosenberg** [comment]
> semantic-release uses Git tags to identify the last commit of a release.
> If you already have releases you should make sure the corresponding commit is tagged with a tag named `v<version>` (for example `v2.0.0`).

@pvdlg where can I find documentation on version tagging? I can't tell from your comment if the version can be first or last in the commit message or if it has to stand alone.

**Comment by Ellosaur** [comment]
I tagged my existing project with `v2.0.0` before running semantic-release and ended up with this:
```
git tag --list
v1.0.0
v2.0.0
```
Obviously it failed to actually publish to npm since version 1.0.0 already exists and has made a mess of the changelog as well. Any idea what I did wrong? @pvdlg
