### ISSUE TITLE
ERR! semantic-release Error: Unable to find repo id for  "..." on Travis

### ISSUE THREAD

**Issue by alvarotrigo** [semantic-release/cli#240]
Having the following error:

> ERR! semantic-release Error: Unable to find repo id for  "..." on Travis

What I did:

```sh
npm install -g semantic-release-cli
semantic-release-cli setup
``` 

Repository is private. 
Default npm registry
Using TravisCI

![screen shot 2018-10-03 at 17 40 50](https://user-images.githubusercontent.com/1706326/46421918-839a7f00-c733-11e8-8145-3069490bfcd3.png)

I've looked into other related issues in this same forum but none seems to provide a solution for my case.

I also tried using `sudo semantic-release-cli setup` and also changing the permissions with `chown -R` to the `.config.` file pointed out in the `--debug` message.

**Comment by alvarotrigo** [comment]
Apparently i created the account in travis-ci.org instead of in travis-ci.com
What a mess they have there...

**Comment by mrlaseptima** [comment]
thanks .
we must create account in travis-ci.org.
