### ISSUE TITLE
feature: dryrun

### ISSUE THREAD

**Issue by unional** [semantic-release/cli#266]
One pain point for using `semantic-release` is that I don't know if the commit messages are written correctly so that `semantic-release` will publish the correct version.

When I discover that, it is too late. e.g. a patch/minor version is released while there is a mis-formated BREAKING CHNAGES comment (notice the typo).

Adding `semantic-release-cli dryrun` would help solving this issue.

I can run it locally before I merge the PR.

**Comment by pvdlg** [comment]
`semantic-release-cli` is used only to set up your project. Adding a dry-run option would not make sense.

There is already a dry-run option in `semantic-release` which is what analyze your commits and make the release: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#dryrun
