### ISSUE TITLE
semantic-release-cli Error: ENOENT: no such file or directory, open './.git/config'

### ISSUE THREAD

**Issue by jessengolab** [semantic-release/cli#268]
I'm getting this error wherein when i install semantic versioning it's trying to find { Error: ENOENT: no such file or directory, open './.git/config' i'm not sure why

**Comment by pvdlg** [comment]
There is no much we can do to help with so few informations...
I'm guessing you are running the CLI from a directory that is not a Git repository...but can't tell for sure.
