### ISSUE TITLE
.travis.yml unchanged after init

### ISSUE THREAD

**Issue by Tbhesswebber** [semantic-release/cli#269]
This is my first time using semantic-release cli and some of the documented and expected behavior did not happen upon running `semantic-release-cli setup` - is the documentation wrong and the behavior that I see expected or is there an issue in the implementation somewhere?

#### Expected Behavior
(according to the [readme](https://github.com/semantic-release/cli/blob/master/README.md)):

>##### Travis CI
>For Travis CI, `semantic-release-cli` performs the following additional steps:
>1. Overwrite your `.travis.yml` file
>	* `after_success`: `npm install -g travis-deploy-once` and `travis-deploy-once "npm run semantic-release"`: run `semantic-release` exactly once after all builds pass
>	* Set other sane defaults: `cache: directories: ~/.npm`, `notifications: email: false`

#### Actual Behavior
No change within `.travis.yml`

#### Things to Note
* an `after_success` script existed prior to execution
* a `cache` entry already existed prior to installation
* no errors were thrown during cli execution, but there was a printed link to a [recipe](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md)

**Comment by gr2m** [comment]
Hi @Tbhesswebber, thanks for reporting the issue. We stopped writing / updating the `.travis.yml` file, I think the latest version logs a message with a link to a URL that describes how to setup a `.travis.yml` file, as people set it up in different ways based on the version they are using. 

If you like you can  send a pull request to update the "Travis CI" section in the README to reflect the change?
