### ISSUE TITLE
Where is the GH_TOKEN and the NPM_TOKEN

### ISSUE THREAD

**Issue by manast** [semantic-release/cli#288]
Ok, so with the risk of asking a stupid question... where is the GH_TOKEN and the NPM_TOKEN that has been generated after running the setup? 
Looks like this:
```
semantic-release-cli setup
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? manast
? What is your npm password? [hidden]
? What is your GitHub username? manast
? What is your GitHub password? [hidden]
? What CI are you using? Travis CI
Please refer to https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md to configure your .travis.yml file.
```
and what now?

**Comment by gr2m** [comment]
When you select Travis in the `What CI are you using?` question, the tokens are stored on Travis CI’s configuration for your repository

![image](https://user-images.githubusercontent.com/39992/60404145-b6ef2a80-9b5a-11e9-8600-b17dc89f5610.png)

**Comment by manast** [comment]
ok, thanks. As a tip, besides asking the questions it would be great if the tool also outputs what it actually is doing the the information you pass to it.

**Comment by gr2m** [comment]
That’s a good idea, PRs welcome :)
