### ISSUE TITLE
Broken travis url

### ISSUE THREAD

**Issue by alvaropinot** [semantic-release/cli#292]
Hi 👋, I came across the following broken link 👇 

```
What CI are you using? Travis CI
Please refer to https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md to configure your .travis.yml file.
```
is a 404 page 

Related code: https://github.com/semantic-release/cli/blob/efb3be5d2006f30fe52c83417d8800c742019872/src/lib/travis.js#L113

**Comment by gr2m** [comment]
Thanks for bringing that up. The correct URL is https://github.com/semantic-release/semantic-release/blob/master/docs/03-recipes/travis.md

The docs were recently reworked by @esciara in https://github.com/semantic-release/semantic-release/pull/1249

We'd appreciate a pull request. Not sure if there are other URLs that need updating
