### ISSUE TITLE
TypeError _.assign is not a function when setup is run

### ISSUE THREAD

**Issue by iamcb** [semantic-release/cli#305]
I just tried to run semantic-release-cli setup and got this error. this happens if i answer yes or now to the first question.

`semantic-release-cli setup
? Is the GitHub repository private? Yes

ERR! semantic-release TypeError: _.assign is not a function
ERR! semantic-release     at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/lib/repository.js:85:7)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:85:5)
ERR! semantic-release     at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/index.js:87:5)
ERR! semantic-release  TypeError: _.assign is not a function
ERR! semantic-release     at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/lib/repository.js:85:7)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:85:5)
ERR! semantic-release     at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/index.js:87:5) {
ERR! semantic-release   stack: 'TypeError: _.assign is not a function\n' +
ERR! semantic-release     '    at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/lib/repository.js:85:7)\n' +
ERR! semantic-release     '    at processTicksAndRejections (internal/process/task_queues.js:85:5)\n' +
ERR! semantic-release     '    at module.exports (/Users/adam/dev/web/rwe/node_modules/semantic-release-cli/src/index.js:87:5)'
ERR! semantic-release }
`

**Comment by AndreasPizsa** [comment]
+1

```
❯ npx semantic-release-cli setup
? Is the GitHub repository private? Yes
ERR! semantic-release TypeError: _.assign is not a function
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/repository.js:85:7)
ERR! semantic-release     at process.internalTickCallback (internal/process/next_tick.js:77:7)
ERR! semantic-release  { TypeError: _.assign is not a function
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/repository.js:85:7)
ERR! semantic-release     at process.internalTickCallback (internal/process/next_tick.js:77:7)
ERR! semantic-release   stack:
ERR! semantic-release    'TypeError: _.assign is not a function\n    at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/rep
ository.js:85:7)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)' }
```

**Comment by gr2m** [comment]
Is this happening on private repositories only? I was not able to reproduce the problem

What `npm` version do you use? I had no problems with 6.12.1

**Comment by iamcb** [comment]
I was on 6.12.0 I just upgraded to 6.12.1 and still have the same error.

**Comment by gr2m** [comment]
It's not about the answer, I wonder why you get asked in the first place. You only get asked if the request to check if the repository exists fails, see 

https://github.com/semantic-release/cli/blob/91d921d9c34504afeeb2bb34fc2f0952a586395b/src/lib/repository.js#L74-L88

It's odd because `_.assign` should exist, we load the entire lodash at https://github.com/semantic-release/cli/blob/91d921d9c34504afeeb2bb34fc2f0952a586395b/src/lib/repository.js#L3.

I recall that we have seen this error or something similar before and we couldn't figure it out. I'd appreciate if you could digg in an try to find out what's happening. I can't help much until I'm able to reproduce the error

**Comment by iamcb** [comment]
My bad, I just set my repo to public to test and yes this error only happens when it's set to private, as it's working now

**Comment by AndreasPizsa** [comment]
> Is this happening on private repositories only? I was not able to reproduce the problem

Private only.

> What npm version do you use? I had no problems with 6.12.1

6.12.0

**Comment by AndreasPizsa** [comment]
Well, line 76 re-declares `_` as the error argument, thus overwriting `lodash` 💡  @gr2m 

https://github.com/semantic-release/cli/blob/91d921d9c34504afeeb2bb34fc2f0952a586395b/src/lib/repository.js#L76

**Comment by gr2m** [comment]
# 🤦‍♂ 

could you send a PR to get that fixed?

**Comment by AndreasPizsa** [comment]
on it

**Comment by AndreasPizsa** [comment]
good to merge after review @gr2m

**Comment by gr2m** [comment]
Thanks a ton @AndreasPizsa 💐
