### ISSUE TITLE
Setup Script Searching for Wrong Repo on Travis

### ISSUE THREAD

**Issue by mateja176** [semantic-release/cli#307]
After running

`semantic-release-cli setup`

and answering each question, the following error is logged: 

```
ERR! semantic-release Error: Unable to find repo id for "https://github.com/mytee306/react-hot-starter.git" on Travis.
ERR! semantic-release     at setUpTravis (~/.nvm/versions/node/v12.13.0/lib/node_modules/semantic-release-cli/src/lib/travis.js:53:13
)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR! semantic-release  Error: Unable to find repo id for "https://github.com/mytee306/react-hot-starter.git" on Travis.
ERR! semantic-release     at setUpTravis (~/.nvm/versions/node/v12.13.0/lib/node_modules/semantic-release-cli/src/lib/travis.js:53:13)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
ERR! semantic-release   stack: 'Error: Unable to find repo id for "https://github.com/mytee306/react-hot-starter.git" on Travis.\n' +
ERR! semantic-release     '    at setUpTravis (~/.nvm/versions/node/v12.13.0/lib/node_modules/semantic-release-cli/src/lib/travis.js:53:13)\n' +
ERR! semantic-release     '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
ERR! semantic-release }
```

One thing obviously stands out and that's the fact that `semantic-release` was searching for `https://github.com/mytee306/react-hot-starter.git` where `mytee306` is my old username which was changed months ago. I assume that the `semantic-release` knows about the username since that was my username at the time of creating the repository, but it still seems odd that it is being brought up.

**Comment by mateja176** [comment]
Related:

#88
#156
#642
#240

**Comment by gr2m** [comment]
what's the `"repository"` field in your package.json?

**Comment by gr2m** [comment]
what's the `"repository"` field in your package.json?

**Comment by mateja176** [comment]
> what's the `"repository"` field in your package.json?

The repository field was causing the issue and after updating it the error went away, thanks!
