### ISSUE TITLE
Error running semantic-release-cli setup , TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by tangzijun** [semantic-release/cli#340]
Error running semantic-release-cli setup.

**run** ： semantic-release-cli setup
? What is your npm registry? http://registry.npmjs.org/
? Which authentication method is this npm registry using? Legacy (username, password, email)
? What is your npm username? zijuntang
? What is your npm password? [hidden]
? What is your npm email address? 223663737@qq.com
? What is your GitHub username? tangzijun
? What is your GitHub password? [hidden]
? What CI are you using? **Github Actions**

**error** : TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined at Function.from (buffer.js:327:9)

![image](https://user-images.githubusercontent.com/11813048/81767412-f1f81380-950a-11ea-9de6-25ae9941766b.png)

**version:** 
- semantic-release-cli  5.3.0
- node  v12.16.3

**Comment by lukebrandonfarrell** [comment]
+1

**Comment by lukebrandonfarrell** [comment]
@tangzijun Could you post here what you did to fix this?
