### ISSUE TITLE
⚠️ Currently broken due to defunkt Basic Auth APIs

### ISSUE THREAD

**Issue by gr2m** [semantic-release/cli#351]
`semantic-release-cli` is currently not working, as it utilizes basic auth for authentication, which is no longer supported by GitHub.

Until we resolve this issue by implementing a OAuth web flow, this is what my usual release GitHub action looks like:
https://github.com/octokit/core.js/blob/master/.github/workflows/release.yml

You don't need to configure the GITHUB_TOKEN, it's already provided. Unless you have actions triggered by the release event, in which case you need to use a personal access token, because actions don't trigger actions.

Hope that helps. Let me know if you have any questions

**Comment by MatthewZito** [comment]
I messed around with this for a good 30 minutes. You'll need to run `semantic-release`, not `semantic-release-cli`. Do `semantic-release --gh-token=yourtoken` (add npm token if needed - mine was already set in npmrc).

**Comment by cujarrett** [comment]
Any update?

**Comment by gr2m** [comment]
Yeah that would be good for the time being. PR welcome

**Comment by cujarrett** [comment]
@gr2m - Please let me know if it looks off.

https://github.com/semantic-release/cli/pull/352

**Comment by gr2m** [comment]
worked around via https://github.com/semantic-release/cli/pull/352
