### ISSUE TITLE
How to use with NX Monorepo

### ISSUE THREAD

**Issue by tomavic** [semantic-release/cli#383]
Hi Maintainers,

I can not find a definite guide on how to run `npx semantic-release-cli setup` with Nx monorepo.

Your help is urgently needed & appreciated

**Comment by travi** [comment]
semantic-release does not officially support monorepos of any type. Some third-party add-ons exist, but are not supported by this team. 

If you need an urgent answer in the future, please search existing issues and discussions. This is a topic that has been covered many times.

**Comment by tomavic** [comment]
That's why I am trying to mention here again as there is no official plugin or any intentions to do so. I have been searching and looking in all the threads for the past 3 months and has developed my own plugins solution for that. However, this still required by many folks ;) .
