### ISSUE TITLE
Need to set Travis header in order to setup

### ISSUE THREAD

**Issue by bahmutov** [semantic-release/cli#69]
Because TravisCI is under DDOS, according to their email, one needs to set the header when making the connection from now on. Otherwise one gets `cannot login, ...` when running `setup` step. 

The change should be done in https://github.com/semantic-release/cli/blob/70ca63b12253378319919c9885c5702c7b7045f5/src/lib/travis.js#L174

```diff
---const travis = info.travis = new Travis({
---  version: '2.0.0'
---})
+++const travis = info.travis = new Travis({
+++  version: '2.0.0',
+++  headers: {
+++    'user-agent': 'Oghliner'
+++  }
+++})
```

Here is the email I received from Travis support

```
It appears your problem stems from the fact that we are currently (and for the last 2 months actually) under a DDoS attack cf. https://www.traviscistatus.com/incidents/bntk781kb8y8. Hence we are currently allowing request only for User-Agent that are whitelisted on our side.

semantic-release-cli is using the travis-ci node module to make requests to our API and the User-Agent it sends is not allowed. So for semantic-release-cli to work again, you would need to both modify travis-ci and semantic-release-cli node module to be able to pass the appropriate header.

Here is a pull request that fixes the travis-ci module: https://github.com/pwmckenna/node-travis-ci/pull/6. Maybe you could fork the semantic-release-cli and try to incorporate a fork of travis-ci's repo that include this fix? Sorry for the inconvenience.
```

**Comment by bahmutov** [comment]
Also, looking at the email and the pull requests, one needs to use the forked travis-ci module https://github.com/mykmelez/node-travis-ci/tarball/e35375de8b06bbe7209b5dfe94f816737002e928

**Comment by bahmutov** [comment]
When doing both locally, the setup worked.

**Comment by jimthedev** [comment]
Who's user agent is this then?

**Comment by jimthedev** [comment]
Oh man. I really want to use your fork temporarily but unfortunately npm won't install it because semantic-release doesn't have a version set in package.json.

**Comment by bahmutov** [comment]
that's the email I got from Travis support. The way I got around the problem was to install semantic-release-cli, then `npm explore -g` then change dist/travis.js and then install the patched version of travis module. ;)
