### ISSUE TITLE
Add option to not remove version field or set it to a custom value

### ISSUE THREAD

**Issue by jimthedev** [semantic-release/cli#71]
In the case of many libraries, removing the version field is problematic because npm seems to check for versions and hard fail if a version field is not set. For example, if you try to npm install a git repo instead of an npm package (say, you've got your own private fork and are waiting on a PR to land) then you'll not be able to proceed without adding a version field to your package.json.

It seems to work just fine to add some benign version like 0.0.0-semantically-released but this would probably be best as an option. I know this is likely blocked by #20 but it seems like a really useful feature given npm's insistence on a version field.

**Comment by jimthedev** [comment]
This will be resolved when #72 gets merged and released. All you need to do is specify `--retain-version` when running setup and the version will no longer get deleted. IMO this should be the default but for backwards compat this accomplishes enough to stop npm from getting mad.

/cc: @kentcdodds

**Comment by kentcdodds** [comment]
Yeah, I prefer setting the `version` to `0.0.0-semantically-released` and that's what my egghead.io lesson does. I would love this to be the default behavior because it communicates to people looking at the repo that this is special and they can look around to understand what that means.
