### ISSUE TITLE
Add "init" as an alternative to "setup"

### ISSUE THREAD

**Issue by lewiscowper** [semantic-release/cli#73]
I keep typing `semantic-release-cli init` instead of `semantic-release-cli setup`, because the other tools I use regularly (`git` and `npm`), use `init` as an initialisation/setup command. It's very much on the developer ergonomics end, and to fix my problem, so I'm happy to take it.

**Comment by boennemann** [comment]
Sure, sounds like a good plan, and I'm happy to get a PR!

I'm wondering if it would make sense to also expose the global bin as `semantic-release`, w/o the obvious `-cli` postfix. It would conflict with the `semantic-release` package then, but I can't think of a use case where they are installed side by side.

`semantic-release init` would overall be a way nicer command.


<sub>Would you mind adding the `init` alias to the greenkeeper CLI as well? :P</sub>
