### ISSUE TITLE
Authentication with Artifactory Online (private npm) doesn't work

### ISSUE THREAD

**Issue by ghengeveld** [semantic-release/cli#79]
I'm trying to setup semantic-release against a private npm package hosted on Artifactory (not the npm public registry), but it fails for me:

```
? Is the GitHub repository private? Yes
? What is your npm registry? https://<customer>.artifactoryonline.com/<customer>/api/npm/blaze-npm-releases/
? What is your npm username? <username>
? What is your npm email? <email>
? What is your npm password? **************************************
ERR! semantic-release Could not login to npm registry. Check your credentials.
ERR! semantic-release Error: 204 Could not create user
ERR! semantic-release undefined
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/adduser.js:112:17
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/adduser.js:73:16
ERR! semantic-release     at f (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/once/once.js:17:25)
ERR! semantic-release     at /Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:68:16
ERR! semantic-release     at f (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/once/once.js:17:25)
ERR! semantic-release     at RegClient.<anonymous> (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:255:12)
ERR! semantic-release     at Request._callback (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/Users/ghengeveld/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/request/request.js:200:22)
ERR! semantic-release     at emitTwo (events.js:87:13)
ERR! semantic-release     at Request.emit (events.js:172:7)
ERR! semantic-release  [Error: 204 Could not create user
ERR! semantic-release undefined]
```

I'm confident the credentials are correct. In fact connecting directly to Artifactory proves this.

`curl -u<username> https://<customer>.artifactoryonline.com/<customer>/api/npm/auth`

That prompts me for the password and gives me back an auth token and the associated email address. 

I've also tried the base64 encoded password and the auth token. Note that my `~/.npmrc` is already setup to correctly handle publishing to Artifactory (for scoped packages) and I have the publishConfig registry setup in package.json too, so I'm a bit surprised semantic-release-cli doesn't just pick that up.

On a related note I think failing to enter the right password should not exit the wizard but provide the option to try again.

**Comment by motanelu** [comment]
+1 - I'm experiencing the same problem.

**Comment by FezVrasta** [comment]
Same problem here, any reply from the maintainer at least?

**Comment by janppires** [comment]
+1

**Comment by ilatypov** [comment]
Allowing the 204 code seems to get me through, but then I got 400 from JFrog 4.7.1 trying to publish.
```diff
@@ -95,7 +95,7 @@

   function done (token, cb) {
     return function (error, data, json, response) {
-      if (!error && (!response || response.statusCode === 201)) {
+      if (!error && (!response || response.statusCode === 201 || response.statusCode == 204)) {
         return cb(error, data, json, response)
       }

```

**Comment by pvdlg** [comment]
Additional info in semantic-release/semantic-release#300

**Comment by kbrandwijk** [comment]
Reading the related issue, it seems that semantic-release supports publishing by setting 'NPM_USERNAME', 'NPM_PASSWORD' and 'NPM_EMAIL'. Does that mean that the CLI should set these three env vars on the CI? If so:
- How should the CLI determine Artifactory NPM? By URL?
- What should the CLI ask the user? username/password/email?

**Comment by pvdlg** [comment]
> How should the CLI determine Artifactory NPM? By URL?

Not sure it's possible as:
- Artifactory can be behind any URL
- Only the Artifactory version < 5.4 require `NPM_USERNAME`, `NPM_PASSWORD` and `NPM_EMAIL`. More recent version support `NPM_TOKEN`
- There might be other npm compatible registry out there that require the legacy auth

> What should the CLI ask the user? username/password/email?

I guess if the registry defined by the user on the first question is not the default npm one, the CLI should ask, something like "Does your registry require legacy auth?". If the user answer yes then yes we should ask the email in addition of the username and password that we already ask.

**Comment by kbrandwijk** [comment]
> I guess if the registry defined by the user on the first question is not the default npm one, the CLI should ask, something like "Does your registry require legacy auth?". If the user answer yes then yes we should ask the email in addition of the username and password that we already ask.

And also skip the step to get the token.

**Comment by kbrandwijk** [comment]
```shell
? Select the authentication method for the selected npm registry:
> Token based
  Legacy
```

**Comment by pvdlg** [comment]
The very very large majority of users will use the default npm registry, and therefore use a token auth.
So as long as we ask this question only to users who do not use the default registry, that's seems good!

**Comment by rodoabad** [comment]
@pvdlg is there other way to debug this?

```
Artifactory Version 6.16.0
Latest Release: 6.17.0
```

We're having a hard time debugging this on our end.

```

[2020-02-29T03:27:23.969Z] npm ERR! code E401

[2020-02-29T03:27:23.969Z] npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"

[2020-02-29T03:27:23.969Z] 

[2020-02-29T03:27:23.969Z] npm ERR! A complete log of this run can be found in:
[2020-02-29T03:27:23.970Z]   exitCode: 1,

[2020-02-29T03:27:23.970Z]   signal: undefined,

[2020-02-29T03:27:23.970Z]   signalDescription: undefined,
```

It was working before `15.13.24` of semantic-release.
